[package]
name = "unstable-problem"
version = "0.1.0"
authors = ["Andrey Kuznetsov <fear@loathing.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2-sys = "0.1"
